apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deltameta-ingress
spec:
  rules:
    - host: deltameta.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deltameta-backend
                port:
                  number: 80

